---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

# Pure-FTPd setup
- name: Create the FTP system group '{{ ftp_group }}'
  group: name={{ ftp_group }} state=present

- name: Create the FTP system user '{{ ftp_user }}'
  user: name={{ ftp_user }} group={{ ftp_group }} home=/dev/null shell=/sbin/nologin state=present

- name: Create FTP server root directory '{{ ftp_root }}'
  file: dest={{ ftp_root }} mode=0755 state=directory owner={{ ftp_user }} group={{ ftp_group}}

- include: tls.yml
  when: enable_tls

# Create the virtual FTP users and set their passwords
- include: virtual-user.yml
  with_items: "{{ virtual_users }}"

- name: Link virtual FTP user database to the correct location
  file: src={{ __ftp_user_db }} dest={{ __ftp_user_db_sym }} state=link

- name: Restart pure-ftpd to pick up configuration changes
  service: name=pure-ftpd state=restarted

# - Ensure that FTP service is running
- name: Ensure pure-ftpd is started and enabled to start at boot.
  service: name=pure-ftpd state=started enabled=yes
