---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400

- name: Ensure pure-ftpd is installed.
  apt:
    name: "pure-ftpd"
    state: installed
    default_release: "{{ pureftpd_default_release }}"